global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'nodejs-app'
  #metrics_path: '/custom-metrics' -->for custom path otherwise prometheus will take /metrics as default 
    static_configs:
      - targets: ['node-app:3000']